baseURL = "https://arcadium.dev"
languageCode = "en-us"
title = "arcadium.dev"
theme = "hemingway2"
copyright = "&copy; 2018-20, Ian Cahoon"
#summaryLength = 0

[taxonomies]
tag = "tags"
category = "categories"

[params]
favicon = "/assets/images/hypercube-32x32.png"
avatar = "/assets/images/hypercube.png"

[params.highlight]
style = "idea"
languages = ["go", "dockerfile", "json", "bash"]

[[params.social]]
url = "https://github.com/arcadium-dev/"
fa_icon = "fab fa-github"

[[params.social]]
url = "https://hub.docker.com/u/arcadium/"
fa_icon = "fab fa-docker"
